#ifndef MMU_H
#define MMU_H

//BUS MEMORY MAP
//16-bit BUS
#define ROM_BANK_00_ADDRESS_START 0
#define ROM_BANK_00_ADDRESS_END 0x3FFF
#define ROM_BANK_01_ADDRESS_START 0x4000
#define ROM_BANK_01_ADDRESS_END 0x7FFF
#define VRAM_ADDRESS_START 0x8000
#define VRAM_ADDRESS_END 0x9FFF
#define EXTERNAL_RAM_ADDRESS_START 0xA000
#define EXTERNAL_RAM_ADDRESS_END 0xBFFF
#define WRAM_BANK_0_ADDRESS_START 0xC000
#define WRAM_BANK_0_ADDRESS_END 0xCFFF
#define WRAM_BANK_1_ADDRESS_START 0xD000
#define WRAM_BANK_1_ADDRESS_END 0xDFFF
#define WRAM_BANK_0_ECHO_ADDRESS_START 0xE000
#define WRAM_BANK_0_ECHO_ADDRESS_END 0xFDFF
#define SPRITE_ATTRIBUTE_TABLE_ADDRESS_START 0xFE00
#define SPRITE_ATTRIBUTE_TABLE_ADDRESS_END 0xFE9F
#define NOT_USABLE_ADDRESS_START 0xFEA0
#define NOT_USABLE_ADDRESS_END 0xFEFF
#define IO_PORTS_ADDRESS_START 0xFF00
#define IO_PORTS_ADDRESS_END 0xFF7F
#define HIGH_RAM_ADDRESS_START 0xFF80
#define HIGH_RAM_ADDRESS_END 0xFFFE
#define INTERRUPT_ENABLE_REGISTER_ADDRESS 0xFFFF

#endif


