#ifndef CPUIOCONTROLLER_H
#define CPUIOCONTROLLER_H

#define IO_REGISTER_FILE_SIZE 128
//
#define JOYPAD_INPUT_REGISTER 0x00
#define SERIAL_TRANSFER_DATA_REGISTER 0x01
#define SERIAL_TRANSFER_CONTROL_REGISTER 0x02
#define DIVIDER_REGISTER 0x04
#define TIMER_COUNTER_REGISTER 0x05
#define TIMER_MODULO_REGISTER 0x06
#define TIMER_CONTROL_REGISTER 0x07
#define INTERRUPT_REGISTER 0x0F
#define SOUND_1_SWEEP 0x10
#define SOUND_1_LENGTH 0x11
#define SOUND_1_VOLUME 0x12
#define SOUND_1_PERIOD_LOW 0x13
#define SOUND_1_PERIOD_HIGH 0x14
#define SOUND_2_LENGTH 0x16
#define SOUND_2_VOLUME 0x17
#define SOUND_2_PERIOD_LOW 0x18
#define SOUND_2_PERIOD_HIGH 0x19
#define SOUND_3_DAC_ENABLE 0x1A
#define SOUND_3_LENGTH 0x1B
#define SOUND_3_VOLUME 0x1C
#define SOUND_3_PERIOD_LOW 0x1D
#define SOUND_3_PERIOD_HIGH 0x1E
#define SOUND_4_LENGTH 0x20
#define SOUND_4_VOLUME 0x21
#define SOUND_4_FREQUENCY 0x22
#define SOUND_4_CONTROL 0x23
#define MASTER_VOLUME 0x24
#define SOUND_PANNING 0x25
#define SOUND_ON_OFF 0x26
#define WAVE_RAM_ADDRESS_START 0x30
#define WAVE_RAM_ADDRESS_END 0x3F
#define BOOT_ROM_LOCK_REGISTER 0x50

void doOpIOPort(unsigned short address, unsigned char* buffer, int mode);

#endif

